# Generated by Django 4.2.30 on 2026-06-06 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0003_alter_answer_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quiz",
            name="question_time_seconds",
        ),
        migrations.AddField(
            model_name="question",
            name="time_limit_seconds",
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name="quiz",
            name="use_quiz_timer",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="quizattempt",
            name="current_question_order",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="quizattempt",
            name="current_question_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="total_time_minutes",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="question",
            unique_together={("quiz", "order")},
        ),
        migrations.AddIndex(
            model_name="answer",
            index=models.Index(
                fields=["question"], name="quizzes_ans_questio_8026ef_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="answer",
            index=models.Index(
                fields=["attempt"], name="quizzes_ans_attempt_f662fd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="quizattempt",
            index=models.Index(fields=["quiz"], name="quizzes_qui_quiz_id_0fc073_idx"),
        ),
        migrations.AddIndex(
            model_name="quizattempt",
            index=models.Index(fields=["user"], name="quizzes_qui_user_id_f3e411_idx"),
        ),
        migrations.AddIndex(
            model_name="quizattempt",
            index=models.Index(
                fields=["completed"], name="quizzes_qui_complet_e17e14_idx"
            ),
        ),
    ]
