# Generated by Django 4.2.30 on 2026-06-10 16:00

from django.db import migrations


def deduplicate_options(apps, schema_editor):
    Option = apps.get_model("quizzes", "Option")
    seen = set()

    for option in Option.objects.order_by("question_id", "option_text", "id"):
        key = (option.question_id, option.option_text)
        if key in seen:
            option.delete()
        else:
            seen.add(key)


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_remove_quiz_question_time_seconds_and_more'),
    ]

    operations = [
        migrations.RunPython(deduplicate_options, migrations.RunPython.noop),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order']},
        ),
        migrations.AlterUniqueTogether(
            name='option',
            unique_together={('question', 'option_text')},
        ),
    ]
