# Generated by Django 4.2.30 on 2026-06-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0005_alter_question_options_alter_option_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='join_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]